import { ICountryCurrency } from '../models/country-currency.interface';

export const COUNTRY_CURRENCY_DATA: ICountryCurrency[] = [
  {
    countryCode: 'VN',
    phoneCode: '84',
    internationalName: 'Vietnam',
    currencySymbol: '₫',
    currencyCode: 'VND',
    angularSymbol: '₫',
  },
  {
    countryCode: 'US',
    phoneCode: '1',
    internationalName: 'United States',
    currencySymbol: '$',
    currencyCode: 'USD',
    angularSymbol: 'US$',
  },
  {
    countryCode: 'AU',
    phoneCode: '61',
    internationalName: 'Australia',
    currencySymbol: '$',
    currencyCode: 'AUD',
    angularSymbol: 'AU$',
  },
  {
    countryCode: 'ES',
    phoneCode: '34',
    internationalName: 'Spain',
    currencySymbol: '€',
    currencyCode: 'EUR',
    angularSymbol: '€',
  },
  {
    countryCode: 'CN',
    phoneCode: '86',
    internationalName: 'China',
    currencySymbol: '¥',
    currencyCode: 'RMB',
    angularSymbol: 'CN¥',
  },
  {
    countryCode: 'ET',
    phoneCode: '251',
    internationalName: 'Ethiopia',
    currencySymbol: 'Br',
    currencyCode: 'ETB',
    angularSymbol: 'ETB',
  },
  {
    countryCode: 'NL',
    phoneCode: '31',
    internationalName: 'Netherlands',
    currencySymbol: '€',
    currencyCode: 'EUR',
    angularSymbol: '€',
  },
  {
    countryCode: 'ZA',
    phoneCode: '27',
    internationalName: 'South Africa',
    currencySymbol: 'R',
    currencyCode: 'ZAR',
    angularSymbol: 'ZAR',
  },
  {
    countryCode: 'NZ',
    phoneCode: '64',
    internationalName: 'New Zealand',
    currencySymbol: '$',
    currencyCode: 'NZD',
    angularSymbol: 'NZ$',
  },
  {
    countryCode: 'IR',
    phoneCode: '972',
    internationalName: 'Israel',
    currencySymbol: '₪',
    currencyCode: 'ILS',
    angularSymbol: '₪',
  },
  {
    countryCode: 'MY',
    phoneCode: '60',
    internationalName: 'Malaysia',
    currencySymbol: 'RM',
    currencyCode: 'MYR',
    angularSymbol: 'MYR',
  },
  {
    countryCode: 'IT',
    phoneCode: '39',
    internationalName: 'Italy',
    currencySymbol: '€',
    currencyCode: 'EUR',
    angularSymbol: '€',
  },
  {
    countryCode: 'CO',
    phoneCode: '57',
    internationalName: 'Colombia',
    currencySymbol: '$',
    currencyCode: 'COP',
    angularSymbol: 'COP',
  },
  {
    countryCode: 'EC',
    phoneCode: '593',
    internationalName: 'Ecuador',
    currencySymbol: '$',
    currencyCode: 'USD',
    angularSymbol: 'US$',
  },
  {
    countryCode: 'JP',
    phoneCode: '81',
    internationalName: 'Japan',
    currencySymbol: '¥',
    currencyCode: 'JPY',
    angularSymbol: '¥',
  },
  {
    countryCode: 'KE',
    phoneCode: '254',
    internationalName: 'Kenya',
    currencySymbol: 'Ksh',
    currencyCode: 'KES',
    angularSymbol: 'KES',
  },
];
